# Site settings
title: "Jimin Lee"
description: "Ph.D. Student in Systems at Georgia Tech"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jimin Lee"
resume_title:                   "Ph.D. Student in Systems at Georgia Tech"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jimin at gatech dot edu"

# the next two items are used for schema itemprops in _layouts/resume.html
#resume_contact_telephone:       "555-7334"
resume_contact_address:         "GTISC Lab, CODA Building 756 West Peachtree ST NW, Atlanta, GA 30332"

resume_header_contact_info:     "GTISC Lab, CODA Building 756 West Peachtree ST NW, Atlanta, GA 30332 • jimin at gatech dot edu"
display_header_contact_info:    "false"

resume_header_intro: "<p>I am broadly interested in storage systems, file systems, distributed systems, and systems with machine 
learning. I am especially interested in building storage systems with higher performance and reliability 
based on NVM and PM." 

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false
resume_section_contactinfo:     true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/leejmn"
#  resume_twitter_url:           "http://twitter.com/jglovier"
#  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/jimin-lee-bb5bb3152/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://leejmn.github.io"
#  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
